version: "3.8"

services:
  minio:
    container_name: minio
    image: quay.io/minio/minio
    ports:
      - "9000:9000" # API
      - "9001:9001" # Web UI
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=root1234
    command: server /data --console-address ":9001"
    volumes:
      - ~/minio/data:/data
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5